name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev

      # Build the project
      - name: Build the Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          # Démarrer le serveur en arrière-plan
          ./rtype_server &

          # Attendre un instant pour laisser le serveur démarrer
          sleep 2

          # Lancer les tests
          ./server_test

          # Tuer le processus du serveur après les tests
          pkill rtype_server || true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Deployment Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y

      - name: Deploy to Local Server
        run: |
          # Copier l'exécutable dans le dossier de déploiement
          mkdir -p deploy
          cp build/rtype_server deploy/

          # Lancer le serveur
          cd deploy
          chmod +x rtype_server
          ./rtype_server &
