name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev

      - name: Build the Project
        run: |
          mkdir -p deploy
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest -V

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Timezone to Avoid Interactive Prompt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
          sudo apt-get update
          sudo apt-get install -y tzdata
          sudo dpkg-reconfigure --frontend noninteractive tzdata

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev
