name: R-Type CI/CD

on:
  push:
    branches:
      - server
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test C++ Server

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev

      # Step 3: Build the project
      - name: Build the Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Step 4: Run unit tests
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Deployment Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client rsync

      - name: Deploy to Server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          rsync -avz -e "ssh -i deploy_key.pem" build/ $DEPLOY_USER@$DEPLOY_SERVER:~/rtype-server/

          ssh -i deploy_key.pem $DEPLOY_USER@$DEPLOY_SERVER "cd ~/rtype-server && ./start-server.sh"
