name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev

      - name: Build the Project
        run: |
          mkdir -p deploy
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest -V

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Deployment Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y

      - name: Deploy to Local Server
        run: |
          nohup ./rtype_server &  # Lancer le serveur en arrière-plan
          sleep 5  # Attendre un peu plus longtemps pour s'assurer que le serveur soit prêt

      - name: Test Deployed Server
        run: |
          # Attente jusqu'à ce que le serveur soit prêt à accepter des connexions
          for i in {1..10}; do
            curl --fail http://localhost:58920 && break  # Si ça réussit, on sort de la boucle
            echo "Tentative de connexion échouée, réessaye..."
            sleep 1  # Attendre avant de réessayer
          done
          curl --fail http://localhost:58920 || exit 1  # Si on échoue après plusieurs tentatives, arrêter


      - name: Stop Server
        run: |
          echo "Arrêt du serveur..."
          pkill -f "rtype_server"  # Arrêter proprement le serveur

