jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev

      - name: Build the Project
        run: |
          mkdir -p deploy
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest -V

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Deploy to Local Server
        run: |
          nohup ./rtype_server &

      - name: Wait for Server to Start
        run: |
          sleep 5  # Attends 5 secondes pour que le serveur démarre correctement

      - name: Test Deployed Server
        run: |
          curl --fail http://localhost:58920 || exit 1

      - name: Send stop signal to server
        run: |
          sleep 5  # Attends encore quelques secondes pour donner le temps au serveur de se fermer
          curl --fail http://localhost:58920 || exit 1  # Vérifie que le serveur est bien arrêté
