name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev

      # Build the project
      - name: Build the Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          ls -l            # Lister les fichiers générés après cmake
          make
          ls -l            # Lister les fichiers générés après make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/



  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Ajoutez cette nouvelle étape au début du job test
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/

      # Ajoutez cette étape pour vérifier le contenu du répertoire build
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build/

      # Votre étape existante "Run Tests" reste inchangée
      - name: Run Tests
        run: |
          ls -l
          cd build


  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Deployment Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y

      - name: Deploy to Local Server
        run: |
          # Copier l'exécutable dans le dossier de déploiement
          mkdir -p deploy
          cp build/rtype_server deploy/

          # Lancer le serveur
          cd deploy
          chmod +x rtype_server
          ./rtype_server &
