name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev

      - name: Build the Project
        run: |
          mkdir -p deploy
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest -V

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy C++ Server

    steps:
      - name: Deploy to Local Server
        run: |
          nohup ./rtype_server &

      - name: Test Deployed Server
        run: |
          sleep 2
          curl --fail http://localhost:18720 || exit 1
