name: R-Type Server CI/CD

on:
  push:
    branches:
      - server
      - main
  pull_request:
    branches:
      - server
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libboost-all-dev libgtest-dev

      - name: Build the Project
        run: |
          mkdir -p deploy
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest -V

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t rtype-server:${{ github.sha }} .

      - name: Run Docker Container Locally
        run: |
          docker stop rtype-server || true
          docker rm rtype-server || true
          docker run -d --name rtype-server -p 2080:2080 rtype-server:${{ github.sha }}