name: Test Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Start server in background
      run: |
        # Démarrer le serveur en arrière-plan
        ./my_server &  # Remplace `my_server` par le nom de ton exécutable de serveur
        # Attendre que le serveur soit prêt avant de faire les tests
        sleep 5  # Le serveur aura quelques secondes pour démarrer
        # Vérifier si le serveur est accessible via curl (tente jusqu'à 10 fois)
        for i in {1..10}; do
          curl --fail http://localhost:53920 && break
          echo "Server not ready yet. Retrying..."
          sleep 2  # Attendre avant de réessayer
        done
        # Si après 10 essais le serveur n'est pas prêt, échouer le test
        if [ $? -ne 0 ]; then
            echo "Server failed to start"
            exit 1
        fi

    - name: Run tests
      run: |
        ./run_tests  # Remplace par la commande que tu utilises pour tes tests

    - name: Stop the server
      run: |
        # Trouver et tuer le processus du serveur en fonction du port
        kill $(lsof -t -i:53920)  # Utiliser le port que ton serveur utilise (53920 ici)
        echo "Server stopped."

    - name: Cleanup
      run: |
        # Action de nettoyage si nécessaire
        echo "Cleanup done."
